/* Words and phrases */

var phrases = [
"The dog is happy",
"I love you",
"A carrot is orange",
"A banana is yellow",
"Peanut butter and jelly",
"Please may I have some",
"The cat has brown fur",
"The sun is out",
"Thank you",
"Please",
"I have a brother",
"I'm playing with my toys",
"I'm watching a show",
"Let's go outside",
"Do you want to play with me?",
"This food is delicious",
"A triangle has three sides",
"A square has four sides",
"A rectangle has four sides",
"The dog is running",
"I love to read",
"The girl has brown hair",
"The boy has a blue shirt",
"Let's listen to some music",
"Blow bubbles",
"I'm playing in the sand box",
"May I have some milk?",
"A cat and a dog",
"I'm tired",
"I'm hungry",
"I'm thirsty",
"I need to go potty",
"The wheels on the bus",
"It's time for bed",
"Clean your room",
"An apple is red",
"The ice cream is cold",
"You are so smart",
"What time is it",
"Tuna fish sandwich",
"Happy birthday"];