/* Words and phrases */

var phrases = ["Jump over pancake",
"The dog is happy",
"I love you",
"A carrot is orange",
"A banana is yellow",
"Peanut butter and jelly",
"The cat has brown fur",
"The sun is out",
"Thank you",
"Please",
"The dog is running",
"I love to read",
"I'm tired",
"I'm hungry",
"The wheels on the bus",
"It's time for bed",
"Clean your room",
"An apple is red",
"The ice cream is cold",
"You are so smart",
"What time is it",
"Tuna fish sandwich",
"Happy birthday"];